import { Car } from "../Models/Car";

export const cars :Car[] = 
    [
new Car({"id":1,"lisenseNumber":"41-380-8906","availability":"Unavailable","carMake":"Pontiac","carModel":"Trans Sport"}),
new Car({"id":2,"lisenseNumber":"17-363-9478","availability":"Booked","carMake":"Dodge","carModel":"Viper RT/10"}),
new Car({"id":3,"lisenseNumber":"81-470-9563","availability":"Available","carMake":"GMC","carModel":"Sierra 1500"}),
new Car({"id":4,"lisenseNumber":"94-410-6565","availability":"Unavailable","carMake":"Mazda","carModel":"RX-7"}),
new Car({"id":5,"lisenseNumber":"77-071-1226","availability":"Unavailable","carMake":"Ford","carModel":"F350"}),
new Car({"id":6,"lisenseNumber":"09-049-9394","availability":"Unavailable","carMake":"Nissan","carModel":"JUKE"}),
new Car({"id":7,"lisenseNumber":"77-094-4777","availability":"Available","carMake":"BMW","carModel":"X3"}),
new Car({"id":8,"lisenseNumber":"88-012-0173","availability":"Available","carMake":"Ferrari","carModel":"430 Scuderia"}),
new Car({"id":9,"lisenseNumber":"11-184-7868","availability":"Booked","carMake":"Chevrolet","carModel":"Blazer"}),
new Car({"id":10,"lisenseNumber":"15-215-5378","availability":"Available","carMake":"Nissan","carModel":"Sentra"}),
new Car({"id":11,"lisenseNumber":"96-727-9791","availability":"Available","carMake":"Buick","carModel":"Century"}),
new Car({"id":12,"lisenseNumber":"90-045-3680","availability":"Booked","carMake":"Ford","carModel":"E-Series"}),
new Car({"id":13,"lisenseNumber":"54-426-0111","availability":"Booked","carMake":"Kia","carModel":"Sportage"}),
new Car({"id":14,"lisenseNumber":"39-185-9383","availability":"Available","carMake":"Chevrolet","carModel":"Colorado"}),
new Car({"id":15,"lisenseNumber":"67-481-2264","availability":"Available","carMake":"Ford","carModel":"Econoline E350"}),
new Car({"id":16,"lisenseNumber":"02-307-0350","availability":"Booked","carMake":"Mercury","carModel":"Montego"}),
new Car({"id":17,"lisenseNumber":"24-926-5105","availability":"Available","carMake":"Maserati","carModel":"Quattroporte"}),
new Car({"id":18,"lisenseNumber":"41-877-9078","availability":"Available","carMake":"Infiniti","carModel":"I"}),
new Car({"id":19,"lisenseNumber":"91-000-8230","availability":"Available","carMake":"Ford","carModel":"Crown Victoria"}),
new Car({"id":20,"lisenseNumber":"70-174-7136","availability":"Unavailable","carMake":"Ford","carModel":"Laser"}),
new Car({"id":21,"lisenseNumber":"39-776-6334","availability":"Available","carMake":"Infiniti","carModel":"G35"}),
new Car({"id":22,"lisenseNumber":"25-775-7437","availability":"Booked","carMake":"Plymouth","carModel":"Colt Vista"}),
new Car({"id":23,"lisenseNumber":"39-506-7157","availability":"Available","carMake":"Hyundai","carModel":"Accent"}),
new Car({"id":24,"lisenseNumber":"40-833-9306","availability":"Available","carMake":"Toyota","carModel":"Echo"}),
new Car({"id":25,"lisenseNumber":"98-551-8062","availability":"Booked","carMake":"Toyota","carModel":"Land Cruiser"}),
new Car({"id":26,"lisenseNumber":"21-560-8707","availability":"Unavailable","carMake":"Mitsubishi","carModel":"Truck"}),
new Car({"id":27,"lisenseNumber":"54-056-5695","availability":"Unavailable","carMake":"Mazda","carModel":"MPV"}),
new Car({"id":28,"lisenseNumber":"77-531-7594","availability":"Unavailable","carMake":"Mitsubishi","carModel":"Galant"}),
new Car({"id":29,"lisenseNumber":"73-148-0968","availability":"Booked","carMake":"Mercury","carModel":"Mariner"}),
new Car({"id":30,"lisenseNumber":"06-685-2226","availability":"Unavailable","carMake":"Mitsubishi","carModel":"Expo LRV"}),
new Car({"id":31,"lisenseNumber":"11-938-1248","availability":"Unavailable","carMake":"Ford","carModel":"Fiesta"}),
new Car({"id":32,"lisenseNumber":"51-158-3962","availability":"Booked","carMake":"Mitsubishi","carModel":"GTO"}),
new Car({"id":33,"lisenseNumber":"39-660-0127","availability":"Unavailable","carMake":"Lotus","carModel":"Esprit"}),
new Car({"id":34,"lisenseNumber":"50-207-7852","availability":"Unavailable","carMake":"Nissan","carModel":"Xterra"}),
new Car({"id":35,"lisenseNumber":"91-790-0863","availability":"Booked","carMake":"Chevrolet","carModel":"Corvette"}),
new Car({"id":36,"lisenseNumber":"38-794-9795","availability":"Booked","carMake":"Lincoln","carModel":"Town Car"}),
new Car({"id":37,"lisenseNumber":"70-192-9910","availability":"Available","carMake":"Mercedes-Benz","carModel":"W201"}),
new Car({"id":38,"lisenseNumber":"45-454-1455","availability":"Available","carMake":"Dodge","carModel":"Avenger"}),
new Car({"id":39,"lisenseNumber":"52-917-9673","availability":"Unavailable","carMake":"Ford","carModel":"Explorer Sport Trac"}),
new Car({"id":40,"lisenseNumber":"65-172-7536","availability":"Booked","carMake":"Saab","carModel":"9-3"}),
new Car({"id":41,"lisenseNumber":"42-882-5563","availability":"Unavailable","carMake":"Jaguar","carModel":"X-Type"}),
new Car({"id":42,"lisenseNumber":"41-028-7014","availability":"Available","carMake":"Audi","carModel":"A6"}),
new Car({"id":43,"lisenseNumber":"98-122-0291","availability":"Available","carMake":"Cadillac","carModel":"XLR"}),
new Car({"id":44,"lisenseNumber":"51-391-4501","availability":"Available","carMake":"Dodge","carModel":"Dakota Club"}),
new Car({"id":45,"lisenseNumber":"33-584-2611","availability":"Booked","carMake":"BMW","carModel":"X5"}),
new Car({"id":46,"lisenseNumber":"19-840-2606","availability":"Available","carMake":"Chevrolet","carModel":"Corvette"}),
new Car({"id":47,"lisenseNumber":"29-073-2894","availability":"Available","carMake":"Buick","carModel":"Regal"}),
new Car({"id":48,"lisenseNumber":"76-871-3588","availability":"Available","carMake":"Chevrolet","carModel":"Corvette"}),
new Car({"id":49,"lisenseNumber":"03-605-3755","availability":"Booked","carMake":"Buick","carModel":"LeSabre"}),
new Car({"id":50,"lisenseNumber":"36-849-6810","availability":"Available","carMake":"Jeep","carModel":"Liberty"})]
}